version: '3'
services:
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    restart: 'always'
    environment:
    - "KIBANA_PWD=root_kibana"
    - "SERVER_NAME=kibana.local"
    - "ELASTICSEARCH_URL=http://elastic:elastic@es01:9200"
    - "ELASTICSEARCH_USERNAME=elastic"
    - "ELASTICSEARCH_PASSWORD=elastic"
    - xpack.security.enabled=true
    volumes:
    - ./bin/kibana/kibana${KIBANA_VERSION}/kibana.yml:/usr/share/kibana/config/kibana.yml
    - ${LIB_VOLUMN}/kibana/log:/var/log/kibana
    ports:
    - ${KIBANA_PORT}:5601
    networks:
    - elastic
    logging:
      options:
        max-size: "50m"
        max-file: "5"

  # Node es01
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es01
    restart: 'always'
    environment:
    - node.name=es01
    - cluster.name=es-docker-cluster
    - discovery.seed_hosts=es02,es03
    - cluster.initial_master_nodes=es01,es02,es03
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms${MEMORY_HEAP_SIZE} -Xmx${MEMORY_HEAP_SIZE}"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    - "ELASTIC_USERNAME=elastic"
    - "ELASTIC_PASSWORD=elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - ${ES7x_DATA_VOLUMN}/data01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - elastic
  # Node es02
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es02
    restart: 'always'
    environment:
    - node.name=es02
    - cluster.name=es-docker-cluster
    - discovery.seed_hosts=es01,es03
    - cluster.initial_master_nodes=es01,es02,es03
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms${MEMORY_HEAP_SIZE} -Xmx${MEMORY_HEAP_SIZE}"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    - "ELASTIC_USERNAME=elastic"
    - "ELASTIC_PASSWORD=elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - ${ES7x_DATA_VOLUMN}/data02:/usr/share/elasticsearch/data
    networks:
    - elastic

  # Node es03
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: es03
    restart: 'always'
    environment:
    - node.name=es03
    - cluster.name=es-docker-cluster
    - discovery.seed_hosts=es01,es02
    - cluster.initial_master_nodes=es01,es02,es03
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms${MEMORY_HEAP_SIZE} -Xmx${MEMORY_HEAP_SIZE}"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    - "ELASTIC_USERNAME=elastic"
    - "ELASTIC_PASSWORD=elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
    - ${ES7x_DATA_VOLUMN}/data03:/usr/share/elasticsearch/data
    networks:
    - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge