version: '3'
services:

  # Nginx
  nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    ports:
      - 8080:80
      - 8090:8090
    environment:
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - PROXY_PASS=http://kibana:5601/
    networks:
      - esnet

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    environment:
      - "KIBANA_PWD=root_kibana"
      - "SERVER_NAME=kibana.local"
      - "ELASTICSEARCH_URL=http://elastic:elastic@es01:9200"
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=elastic"
      - xpack.security.enabled=true
    volumes:
      - ./bin/kibana/kibana${KIBANA_VERSION}/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${LIB_VOLUMN}/kibana/log:/var/log/kibana
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - esnet
    logging:
      options:
        max-size: "50m"
        max-file: "3"

  # ES01
  es01:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic01:${ES_VERSION}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_USERNAME="elastic"
      - ELASTIC_PASSWORD="elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${ES_DATA_VOLUMN}/esdata1:/usr/share/elasticsearch/data
      - ./bin/elastic/elastic${ES_VERSION}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - ${ES_PORT}:9200
    networks:
      - esnet

  # ES02
  es02:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic02:${ES_VERSION}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es01"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${ES_DATA_VOLUMN}/esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  # ES03
  es03:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic03:${ES_VERSION}
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es01"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${ES_DATA_VOLUMN}/esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet

  # Elasticsearch HQ
  elasticsearchHq:
    image: elastichq/elasticsearch-hq
    ports:
      - ${ES_HQ}:5000
    networks:
      - esnet

  #Log stash
#  logstash:
#    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
#    volumes:
#      - ./bin/logstash/logtash${LOGSTASH_VERSION}/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
#      - ./bin/logstash/logtash${LOGSTASH_VERSION}/logstash.yml/:/usr/share/logstash/config/logstash.yml
#    networks:
#      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
