version: '3'
services:
  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elastic:elastic@es01:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
    volumes:
      - ./bin/kibana/kibana${KIBANA_VERSION}/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /data_host6x/kibana/log:/var/log/kibana
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - esnet

  # ES01
  es01:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic01:${ES_VERSION}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_USERNAME= "elastic"
      - ELASTIC_PASSWORD= "elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data_host6x/esdata1:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - esnet

  # ES02
  es02:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic02:${ES_VERSION}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es01"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data_host6x/esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  # ES03
  es03:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic03:${ES_VERSION}
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=es01"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data_host6x/esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet

#  # headPlugin
#  headPlugin:
#    image: 'mobz/elasticsearch-head:5'
#    ports:
#      - 9100:9100
#    networks:
#      - esnet
#
  # Elasticsearch HQ
#  elasticsearchHq:
#    image: elastichq/elasticsearch-hq
#    ports:
#      - ${ES_HQ}:5000
#    networks:
#      - esnet

  # Log stash
#  logstash:
#    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
#    volumes:
#      - ./bin/logstash/logtash${LOGSTASH_VERSION}/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
#      - ./bin/logstash/logtash${LOGSTASH_VERSION}/logstash.yml/:/usr/share/logstash/config/logstash.yml
#    networks:
#      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
