version: '3'
services:
  # ES01
  es01:
    build:
      context: ./bin/elastic/elastic${ES_VERSION}
      dockerfile: Dockerfile
    image: elastic01:${ES_VERSION}
    environment:
#      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
#      - discovery.zen.minimum_master_nodes=2
      - ELASTIC_USERNAME="elastic"
      - ELASTIC_PASSWORD="elastic"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${ES_DATA_VOLUMN}/esdata1:/usr/share/elasticsearch/data
      - ./bin/elastic/elastic${ES_VERSION}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - ${ES_PORT}:9200
    networks:
      - esnet

volumes:
  esdata01:
    driver: local

networks:
  esnet:
    driver: bridge
